name: Streetertech
favicon: null
layout_spectrum: 0.13909582537598908
typography_spectrum: 0.8123875882010907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2123274642508477
  lightness: 0.4621777003630996
  saturation: 0.045943729346618056
  rhythmicContrast: 0.2262155159842223
purpose: []
