name: Streetertech
favicon: null
layout_spectrum: 0.50993
typography_spectrum: 0.58241
title: Streeter Technologies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2f58'
    - '#02719f'
    - '#030305'
    - '#828284'
  brandStrength: 0.2123274642508477
  lightness: 0.3125
  saturation: 0.045943729346618056
  rhythmicContrast: 0.2262155159842223
purpose: []
